name: Release

on:
  workflow_dispatch:
  push:
    branches:
    - test-workflow

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'maven'
    - name: Publish to Maven
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # run: mvn -B deploy
      # env:
      #   MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      #   MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    - name: Release
      uses: softprops/action-gh-release@v2
